module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/LbmbY5xzVXS98KCt6XDWsF?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/SqvcFPd/Rashmika-Ofc.jpg',
    NEWSLETTER_JID: '120363405871120956@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'Tʜᴇ Cᴏᴅᴇꜱ Cʀᴇᴡ Mɪɴɪ',
    OWNER_NAME: 'Qᴜᴇᴇɴ Hᴀɴꜱɪ',
    OWNER_NUMBER: '94769194547',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> *ᴛʜᴇ ᴄᴏᴅᴇꜱ ᴄʀᴇᴡ ᴍᴅ ᴍɪɴɪ ʙᴏᴛ*',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbCG0yxEwEk21tFzPT16',
};
